In [1]:
# ============================================================
# Session 19: Composition Featurization using Matminer
# Magpie and Deml Feature Benchmark
# ============================================================

import pandas as pd
import time

from pymatgen.core import Composition
from matminer.featurizers.composition import ElementProperty

# ------------------------------------------------------------
# 1. Load the cleaned materials dataset
# ------------------------------------------------------------

df = pd.read_csv('cleaned_cp_dataset.csv')

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)

# Check whether the formula column exists
if 'formula' not in df.columns:
    raise KeyError("The dataset must contain a 'formula' column.")

# ------------------------------------------------------------
# 2. Convert chemical formulas into Composition objects
# ------------------------------------------------------------

print("\nConverting formulas into Composition objects...")

df['composition'] = df['formula'].apply(Composition)

print("Composition conversion completed!")

# ------------------------------------------------------------
# 3. Magpie Featurization
# ------------------------------------------------------------

print("\nGenerating Magpie features...")

magpie_feat = ElementProperty.from_preset(
    preset_name='magpie'
)

t0 = time.time()

df_magpie = magpie_feat.featurize_dataframe(
    df[['composition']].copy(),
    col_id='composition'
)

magpie_time = time.time() - t0

print("Magpie featurization completed!")

# ------------------------------------------------------------
# 4. Deml Featurization
# ------------------------------------------------------------

print("\nGenerating Deml features...")

deml_feat = ElementProperty.from_preset(
    preset_name='deml'
)

t0 = time.time()

df_deml = deml_feat.featurize_dataframe(
    df[['composition']].copy(),
    col_id='composition'
)

deml_time = time.time() - t0

print("Deml featurization completed!")

# ------------------------------------------------------------
# 5. Comparative Metrics
# ------------------------------------------------------------

print("\n=== Featurization Benchmark ===")

magpie_feature_count = df_magpie.shape[1] - 1
deml_feature_count = df_deml.shape[1] - 1

print(
    f"Magpie features generated: {magpie_feature_count} "
    f"| Time: {magpie_time:.2f}s"
)

print(
    f"Deml features generated:   {deml_feature_count} "
    f"| Time: {deml_time:.2f}s"
)

# ------------------------------------------------------------
# 6. Export Features for Downstream Selection
# ------------------------------------------------------------

df_magpie.drop(
    columns=['composition'],
    errors='ignore'
).to_csv(
    'matminer_magpie_features.csv',
    index=False
)

df_deml.drop(
    columns=['composition'],
    errors='ignore'
).to_csv(
    'matminer_deml_features.csv',
    index=False
)

print("\nFeatures successfully saved for Session S20.")

# ------------------------------------------------------------
# 7. Display Dataset Information
# ------------------------------------------------------------

print("\n=== Output Dataset Information ===")
print("Magpie dataset shape:", df_magpie.shape)
print("Deml dataset shape:", df_deml.shape)

print("\nFirst 5 rows of Magpie features:")
display(df_magpie.head())

print("\nFirst 5 rows of Deml features:")
display(df_deml.head())

Dataset loaded successfully!
Dataset shape: (4564, 3)

Converting formulas into Composition objects...
Composition conversion completed!

Generating Magpie features...

ElementProperty:   0%|          | 0/4564 [00:00<?, ?it/s]

Magpie featurization completed!

Generating Deml features...

ElementProperty:   0%|          | 0/4564 [00:00<?, ?it/s]

Deml featurization completed!

=== Featurization Benchmark ===
Magpie features generated: 132 | Time: 536.71s
Deml features generated:   80 | Time: 532.90s

Features successfully saved for Session S20.

=== Output Dataset Information ===
Magpie dataset shape: (4564, 133)
Deml dataset shape: (4564, 81)

First 5 rows of Magpie features:

,composition,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,MagpieData range MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,"(B, O)",5.0,8.0,3.0,6.8,1.44,8.0,72.0,87.0,15.0,...,0.0,0.0,0.0,0.0,12.0,166.0,154.0,73.6,73.92,12.0
1,"(B, O)",5.0,8.0,3.0,6.8,1.44,8.0,72.0,87.0,15.0,...,0.0,0.0,0.0,0.0,12.0,166.0,154.0,73.6,73.92,12.0
2,"(B, O)",5.0,8.0,3.0,6.8,1.44,8.0,72.0,87.0,15.0,...,0.0,0.0,0.0,0.0,12.0,166.0,154.0,73.6,73.92,12.0
3,"(B, O)",5.0,8.0,3.0,6.8,1.44,8.0,72.0,87.0,15.0,...,0.0,0.0,0.0,0.0,12.0,166.0,154.0,73.6,73.92,12.0
4,"(B, O)",5.0,8.0,3.0,6.8,1.44,8.0,72.0,87.0,15.0,...,0.0,0.0,0.0,0.0,12.0,166.0,154.0,73.6,73.92,12.0

First 5 rows of Deml features:

,composition,DemlData minimum atom_num,DemlData maximum atom_num,DemlData range atom_num,DemlData mean atom_num,DemlData std_dev atom_num,DemlData minimum atom_mass,DemlData maximum atom_mass,DemlData range atom_mass,DemlData mean atom_mass,...,DemlData minimum mus_fere,DemlData maximum mus_fere,DemlData range mus_fere,DemlData mean mus_fere,DemlData std_dev mus_fere,DemlData minimum FERE correction,DemlData maximum FERE correction,DemlData range FERE correction,DemlData mean FERE correction,DemlData std_dev FERE correction
0,"(B, O)",5,8,3,6.8,2.12132,10.811,15.9994,5.1884,13.92404,...,-4.76,-3.934405,0.825595,-4.429762,0.583784,0.093176,0.23,0.136824,0.175271,0.096749
1,"(B, O)",5,8,3,6.8,2.12132,10.811,15.9994,5.1884,13.92404,...,-4.76,-3.934405,0.825595,-4.429762,0.583784,0.093176,0.23,0.136824,0.175271,0.096749
2,"(B, O)",5,8,3,6.8,2.12132,10.811,15.9994,5.1884,13.92404,...,-4.76,-3.934405,0.825595,-4.429762,0.583784,0.093176,0.23,0.136824,0.175271,0.096749
3,"(B, O)",5,8,3,6.8,2.12132,10.811,15.9994,5.1884,13.92404,...,-4.76,-3.934405,0.825595,-4.429762,0.583784,0.093176,0.23,0.136824,0.175271,0.096749
4,"(B, O)",5,8,3,6.8,2.12132,10.811,15.9994,5.1884,13.92404,...,-4.76,-3.934405,0.825595,-4.429762,0.583784,0.093176,0.23,0.136824,0.175271,0.096749